#!/usr/bin/env bash
# Function to display information about subdomains

display_info() {
    local domain="$1"
    local subdomain="$2"
    
    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short "$sub"."$domain" | awk '{print $1}')
        record_type=$(dig +short "$sub"."$domain" | awk '{print $4}')
        echo "The subdomain $sub is A$record_type record and points to $record"
    done
}

domain="$1"
subdomain="$2"

display_info "$domain" "$subdomain"
