#!/usr/bin/env bash
# Function to display information about subdomains

display_info() {
    local domain="$1"
    local subdomain="$2"
    local text

    text=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
    echo "$subdomain $text" | awk '{printf "The subdomain $1 is a $2 record and points to $3\n"}'
}

if [ "$#" -eq 1 ]; then
	display_info "$1" "www"
	display_info "$2" "lb-01"
	display_info "$3" "web-01"
	display_info "$4" "web-02"
elif [ "$#" -eq 2 ]; then
	display_info "$1" "$2"
fi
