#!/usr/bin/env bash
# Function to display information about subdomain

display_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$domain" +short -t ANY | head -n1 | awk '{print $4}')
        destination=$(dig "$sub.$domain" +short | head -n1)
        echo "The subdomain $sub is a A $record_type record and points to $destination"
    done
}

if [ "$#" -eq 1 ]; then
    display_info "$1"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    exit 1
fi
