#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
path="$(cd "${BASH_SOURCE[0]}" || exit) >/dev/null 2>&1 && pwd)"
file="$1"
ip_key="$2"
username="$3"
ssh_key="$4"

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path"/"$file" "$username@$ip_key":/home/"$username"/