#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

path_file="$1"
ip_key="$2"
username="$3"
path_ssh_key="$4"
filename=$(basename "${BASH_SOURCE[0]}")
brown='\e[0;33m'
reset='\033[0m'

if [ $# -lt 4 ]; then
	echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
else
	scp -o StrictHostChecking=no -i "$path_file" "$path_ssh_key" "$username@$ip_key":~
fi
