#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

file="$1"
ip_key="$2"
username="$3"
ssh_key="$4"
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "${BASH_SOURCE[0]}")
brown='\e[0;33m'
reset='\033[0m'

if [ $# -eq 4 ]; then
    scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path"/"$file" "$username@$ip_key":/home/"$username"/
else
    echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi