#!/usr/bin/env bash
# The redirection must be a “301 Moved Permanently”
# commands to automatically configure a Ubuntu machine to respect above requirements


# install Nginx
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

# starting Nginx service
sudo service nginx start

# allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Redirect to Youtube link
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 ERROR
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart