#!/usr/bin/env bash
# Configure Nginx on your Ubuntu machine for custom 404 page

# Install Nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index for the custom 404 page
echo -e "<html><head><title>404 Not Found</title></head><body><p>Ceci n'est pas une page</p></body></html>" | dd status=none of=/var/www/html/404.html

# Create a custom Nginx configuration file for the custom 404 page
echo -e "server {\n\tlisten 80;\n\tserver_name _;\n\tlocation / {\n\t\troot /var/www/html;\n\t\tindex index.html index.htm;\n\t}\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n}" | sudo tee /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default Nginx configuration for the default site
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
