#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Install Nginx
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.html /var/www/html/index.html.bckp

# Creating a new index
echo -e "Hello World!" > /var/www/html/index.html

# Set up a 404 ERROR and add custom header
echo "Ceci n'est pas une page" >> /var/www/html/404.html

# Use tee to avoid permission issues with sed
custom_header="add_header X-Served-By \$HOSTNAME;"
echo "$custom_header" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Link sites-available to sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restarting Nginx
sudo service nginx restart

