#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi

var='Best School'

i=1
while [[ $i -le 10 ]] ; do
    if [[ $i -eq 9 ]];
    then
        echo "$var"
        echo "Hi"
    else
        echo "$var"
    fi
    (( i += 1 ))
done