#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# -> display hours from 0 to 12
# -> display minutes from 1 to 59

hour=0
echo "Hour: $hour"

while [[ $hour -le 11 ]] ; do
    j=1
    while [[ $j -le 59 ]] ; do
        echo "$j"
        if [[ $j -eq 59 ]] ;
        then
            (( hour += 1 ))
            echo "Hour: $hour"
        fi
        (( j += 1 ))
    done
done