#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# -> localhost resolves to 127.0.0.2
# -> facebook.com resolves to 8.8.8.8.

tmpfile=$(mktemp)

echo "127.0.0.2     localhost" >> "$tmpfile"
echo "8.8.8.8       facebook.com" >> "$tmpfile"

sudo tee /etc/hosts < "$tmpfile" >/dev/null

rm "$tmpfile"